"""cookie 运行副本（run-file）隔离的护栏。

yt-dlp 每次 `--cookies <file>` 运行结束都会把它内存里的 jar 回写进那个文件（固有行为，
没有 CLI 开关能关）。若直接把 Sentinel 真相源交给它，一次被拒的 YouTube 会话就会把
「已登出」jar 写回、永久抹掉 `.youtube.com` 的 LOGIN_INFO。`cookie_runfile` 的职责：把
真相源原样字节拷到一份用完即弃的临时副本，让回写只落在副本上。

核心不变量（`test_writeback_to_runfile_never_touches_truth_source`）刻意**不依赖 yt-dlp**：
不管消费方对拿到的 cookiefile 做了什么，真相源字节都不能变。这比真的调用 yt-dlp 更稳——
它不随 yt-dlp 的实现漂移，只钉死「副本可被随意破坏、真相源纹丝不动」这一条契约。

`CookieSentinel` 是单例，且 `_base_dir` 会**忽略**数据目录 override、直指仓库真实 `bin/`。
所有测试必须先把 `_base_dir` 挪到 tmp_path，否则会碰到开发者本机的真实凭据。
"""

import glob
import os
import sys
import tempfile
import time
from pathlib import Path

# config_manager / logger 在 import 期就会落地文件，先把数据目录挪到临时目录
os.environ.setdefault("FLUENTYTDL_DATA_DIR_OVERRIDE", tempfile.mkdtemp(prefix="fytdl-runfile-"))
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import pytest  # noqa: E402

from fluentytdl.auth.cookie_runfile import (  # noqa: E402
    cookie_runfile,
    sweep_stale_cookie_runfiles,
)
from fluentytdl.auth.cookie_sentinel import cookie_sentinel  # noqa: E402


def _ck_temp_files() -> list[str]:
    """当前系统临时目录里所有 `fluentytdl_ck_*.txt` 运行副本。"""
    return glob.glob(os.path.join(tempfile.gettempdir(), "fluentytdl_ck_*.txt"))


@pytest.fixture
def sentinel(tmp_path, monkeypatch):
    """把单例真相源目录挪进 tmp_path，绝不碰仓库 bin/ 里的真实凭据。

    `_base_dir` 是关键：`get_cookie_path_for_platform()` 与 `_is_managed_truth_source()`
    都从它派生真相源路径。`cookie_path` / `meta_path` 一并挪走，与
    `test_cookie_truth_source.py` 的夹具保持一致。
    """
    monkeypatch.setattr(cookie_sentinel, "_base_dir", tmp_path)
    monkeypatch.setattr(cookie_sentinel, "cookie_path", tmp_path / "cookies_youtube.txt")
    monkeypatch.setattr(cookie_sentinel, "meta_path", tmp_path / "cookies_youtube.txt.meta")
    return cookie_sentinel


# ==================== 核心不变量（独立于 yt-dlp） ====================


def test_writeback_to_runfile_never_touches_truth_source(sentinel):
    """消费方（模拟 yt-dlp 回写）把副本整个改写，真相源字节纹丝不动，副本随后被删除。

    这条测试不调用 yt-dlp —— 它只断言 `cookie_runfile` 给出的是一份可被随意破坏的副本，
    而真相源在整个 `with` 生命周期前后逐字节一致。
    """
    truth = sentinel.get_cookie_path_for_platform("youtube")
    truth.write_bytes(
        b"# Generated by FluentYTDL AuthService\n"
        b".youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tv-login\n"
    )
    before = truth.read_bytes()

    with cookie_runfile(str(truth)) as cf:
        assert cf is not None
        assert Path(cf) != truth  # 拿到的不是真相源本身
        assert Path(cf).read_bytes() == before  # 而是逐字节副本
        Path(cf).write_bytes(b"DESTROYED-BY-YTDLP-LOGGED-OUT-JAR")  # 模拟回写登出态
        leaked = cf

    assert truth.read_bytes() == before  # 真相源不受任何影响
    assert not os.path.exists(leaked)  # 副本随 with 退出被确定性删除


def test_runfile_deleted_even_when_consumer_raises(sentinel):
    """消费方中途抛异常也要删掉副本（finally 语义），真相源仍不变。"""
    truth = sentinel.get_cookie_path_for_platform("youtube")
    truth.write_bytes(b".youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tv\n")
    before = truth.read_bytes()

    leaked: dict[str, str | None] = {"path": None}
    with pytest.raises(RuntimeError):
        with cookie_runfile(str(truth)) as cf:
            leaked["path"] = cf
            raise RuntimeError("boom mid-run")

    assert truth.read_bytes() == before
    assert leaked["path"] is not None
    assert not os.path.exists(leaked["path"])


def test_twitter_truth_source_is_also_isolated(sentinel):
    """两个真相源都要隔离：twitter 真相源同样走副本，不被回写污染。"""
    truth = sentinel.get_cookie_path_for_platform("twitter")
    truth.write_bytes(b".x.com\tTRUE\t/\tTRUE\t0\tauth_token\tv\n")
    before = truth.read_bytes()

    with cookie_runfile(str(truth)) as cf:
        assert Path(cf) != truth
        Path(cf).write_bytes(b"x")

    assert truth.read_bytes() == before


# ==================== 直通：非托管文件 / None ====================


def test_non_managed_path_passes_through_untouched(tmp_path, sentinel):
    """用户自管文件（非真相源）原样直通，不产生任何副本。"""
    user_file = tmp_path / "my_cookies.txt"
    user_file.write_text("user managed\n", encoding="utf-8")

    before_temps = set(_ck_temp_files())
    with cookie_runfile(str(user_file)) as cf:
        assert cf == str(user_file)  # 就是原路径，未被替换
        assert set(_ck_temp_files()) == before_temps  # 期间没多出临时副本
    assert set(_ck_temp_files()) == before_temps


def test_none_passes_through(sentinel):
    """无 Cookie（None）直通，不触发任何文件系统操作。"""
    with cookie_runfile(None) as cf:
        assert cf is None


# ==================== 启动兜底清理 ====================


def test_sweep_removes_stale_but_keeps_fresh(sentinel):
    """启动兜底：够旧的漏网副本被清掉，够新的（可能正被并发实例占用）保留。"""
    tmpdir = Path(tempfile.gettempdir())
    old = tmpdir / "fluentytdl_ck_stale_unittest.txt"
    fresh = tmpdir / "fluentytdl_ck_fresh_unittest.txt"
    old.write_text("x", encoding="utf-8")
    fresh.write_text("y", encoding="utf-8")
    two_hours_ago = time.time() - 7200
    os.utime(old, (two_hours_ago, two_hours_ago))

    try:
        removed = sweep_stale_cookie_runfiles(min_age_seconds=3600.0)
        assert not old.exists()  # 够旧 → 删
        assert fresh.exists()  # 够新 → 留
        assert removed >= 1
    finally:
        for p in (old, fresh):
            try:
                p.unlink()
            except OSError:
                pass
