"""Display-only messages shared across non-QObject services.

Markers below are generated from literal tr_text/log_text calls by i18n_update.
The text is translated before interpolation; never pass a formatted source.
"""

from __future__ import annotations

from PySide6.QtCore import QT_TRANSLATE_NOOP, QCoreApplication


class DisplayText(str):
    """Carry a template through service returns without changing str APIs."""

    def __new__(cls, value: str, source: str, args: tuple, kwargs: dict):
        obj = super().__new__(cls, value)
        obj.message_source = source
        obj.message_args = args
        obj.message_kwargs = kwargs
        return obj

    def __reduce__(self):
        return type(self), (str(self), self.message_source, self.message_args, self.message_kwargs)


def tr_text(source: str, *args, **kwargs) -> str:
    translated = QCoreApplication.translate("RuntimeText", source)
    value = translated.format(*args, **kwargs) if args or kwargs else translated
    return DisplayText(value, source, args, kwargs)


# BEGIN GENERATED MARKERS
# fmt: off
_SOURCES = (
    QT_TRANSLATE_NOOP("RuntimeText", "\n\n建议操作：\n{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n\n提示: X 平台需要登录才能下载部分内容。请在设置中登录 X 平台获取 Cookie。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n\n提示: YouTube 会在浏览器标签页中频繁轮换账号 cookies。官方建议用无痕/隐私窗口登录后导出 youtube.com cookies，并立即关闭无痕窗口，以避免 cookies 被轮换。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n\n提示: 检测到已启用代理，部分代理/出口 IP 会显著增加平台风控概率。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n... (还有 {0} 行)"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n……另有 {0} 项，详见日志"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n⏳ 关键 Cookie 将在 {0} 分钟后过期，建议尽快刷新"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n⚠️ 关键 Cookie 已过期，请立即刷新"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n当前使用的是系统 PATH 上的版本，更新会在应用自带目录下安装一份并优先使用。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n提示: YouTube 正在逐步强制 PO Token。若仅靠 cookies 仍触发验证，可在设置中填写 PO Token，并让 yt-dlp 走 mweb 客户端（官方推荐路径）。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n运行库带有下载来源标记，可能被系统阻止加载。请确认压缩包来自官方且校验正确，在文件属性中解除锁定后重新解压。"),
    QT_TRANSLATE_NOOP("RuntimeText", "\n运行库文件缺失，请重新完整解压或使用安装包覆盖安装。"),
    QT_TRANSLATE_NOOP("RuntimeText", "    迁移冲突: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "    迁移失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  .exe.old → {0} 已还原"),
    QT_TRANSLATE_NOOP("RuntimeText", "  .exe.old 已删除"),
    QT_TRANSLATE_NOOP("RuntimeText", "  .exe.old 清理失败（主程序启动时会重试）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  CreateProcessWithTokenW 失败 (err={0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  CreateProcessWithTokenW 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  DuplicateTokenEx 失败 (err={0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  DuplicateTokenEx 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  FluentYTDL {0} 启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "  ShellExecuteExW 失败 (err={0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  ShellExecuteExW 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  ShellExecuteExW 成功但未返回进程句柄"),
    QT_TRANSLATE_NOOP("RuntimeText", "  TerminateProcess 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  _internal_old/ → _internal/ 已还原"),
    QT_TRANSLATE_NOOP("RuntimeText", "  _internal_old/ 已删除"),
    QT_TRANSLATE_NOOP("RuntimeText", "  _internal_old/ 清理未完全（主程序启动时会重试）"),
    QT_TRANSLATE_NOOP("RuntimeText", "  linked token: GetTokenInformation(TokenLinkedToken) 失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "  shell token: GetShellWindow 返回 0（Explorer 未运行？）"),
    QT_TRANSLATE_NOOP("RuntimeText", "  shell token: OpenProcess 失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "  shell token: OpenProcessToken 失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "  spawn updater 自更新 helper 失败（.new 保留，下次重试）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  updater.exe 已就地替换（目标未被占用）"),
    QT_TRANSLATE_NOOP("RuntimeText", "  {0:<16} 未安装"),
    QT_TRANSLATE_NOOP("RuntimeText", "  {0}: CreateProcessWithTokenW 未成功，退化到 ShellExecuteExW"),
    QT_TRANSLATE_NOOP("RuntimeText", "  {0}: 复制 primary token 失败，退化到 ShellExecuteExW"),
    QT_TRANSLATE_NOOP("RuntimeText", "  使用退化路径 ShellExecuteExW（新版将继承管理员令牌）"),
    QT_TRANSLATE_NOOP("RuntimeText", "  删除新版 exe 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  原用户 SID: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  取 linked token 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  取 shell token 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  可执行文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  启动旧版本..."),
    QT_TRANSLATE_NOOP("RuntimeText", "  安装类型: {0} | 路径: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  完整输出见日志。"),
    QT_TRANSLATE_NOOP("RuntimeText", "  就地替换不可行（{0}），改用退出后 helper"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已 spawn updater 自更新 helper: {0} → {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已删除同批投递的 updater.exe.new（该构建被判定为坏）"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已启动新版 (pid={0})，注意：该实例以管理员权限运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已提权实例: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已用 {0} 降权启动新版 (pid={1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  已通知外壳刷新图标缓存"),
    QT_TRANSLATE_NOOP("RuntimeText", "  归档: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  归档文件已删除"),
    QT_TRANSLATE_NOOP("RuntimeText", "  打开自身令牌失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  数据目录: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  数据迁移报告:"),
    QT_TRANSLATE_NOOP("RuntimeText", "  旧版本已启动 (pid={0}, mode={1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  没有任何一级令牌的身份等于原用户（典型为 OTS 提权），不自动启动新版"),
    QT_TRANSLATE_NOOP("RuntimeText", "  目标: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  看门狗判定: {0} (elapsed={1:.1f}s, alive={2})"),
    QT_TRANSLATE_NOOP("RuntimeText", "  移动: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  组件版本:"),
    QT_TRANSLATE_NOOP("RuntimeText", "  终止未能就绪的新版本进程..."),
    QT_TRANSLATE_NOOP("RuntimeText", "  警告: CreateEnvironmentBlock 失败，退回继承父进程环境"),
    QT_TRANSLATE_NOOP("RuntimeText", "  警告: 无法删除陈旧的 .update_ready: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  警告: 旧版本未能自动启动，需用户手动启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "  警告: 未收到 --origin-user-sid（旧主程序），跳过身份校验，只看完整性级别"),
    QT_TRANSLATE_NOOP("RuntimeText", "  读取令牌 SID 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  跳过: .new 与 updater.exe 解析到同一路径"),
    QT_TRANSLATE_NOOP("RuntimeText", "  跳过受保护条目（归档不该含它）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  还原 _internal 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  还原 exe 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  选定降权级别: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  通知外壳刷新图标缓存失败（无害）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "  飞行前检查通过: base_library.zip + {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", " (缓存可能过期)"),
    QT_TRANSLATE_NOOP("RuntimeText", " 等"),
    QT_TRANSLATE_NOOP("RuntimeText", " 等 {0} 项"),
    QT_TRANSLATE_NOOP("RuntimeText", "### 错误描述\n自动捕获到的错误：\n**{0}**\n\n### 错误日志\n```text\n{1}\n```\n\n### 其他信息\n- FluentYTDL 版本: \n- 操作系统: \n"),
    QT_TRANSLATE_NOOP("RuntimeText", "(取不到)"),
    QT_TRANSLATE_NOOP("RuntimeText", "(未提供)"),
    QT_TRANSLATE_NOOP("RuntimeText", "(未解析出)"),
    QT_TRANSLATE_NOOP("RuntimeText", "- YouTube: https://www.youtube.com/watch?v=... 或 https://youtu.be/...\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "1. {0} 未安装或未登录相关平台\n2. {1} Cookie 数据库被锁定（请关闭浏览器）\n\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "2D 全景"),
    QT_TRANSLATE_NOOP("RuntimeText", "3D 立体 (上下)"),
    QT_TRANSLATE_NOOP("RuntimeText", "3D 立体 (左右/Mesh)"),
    QT_TRANSLATE_NOOP("RuntimeText", "7za 解压失败 (exit {0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "=== 子进程启动 === PID={0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Arc 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "AtomicParsley 不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "AtomicParsley 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "AtomicParsley 封面嵌入成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "AtomicParsley 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "AtomicParsley 错误: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Brave 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "COMMIT: 新版本已就绪，清理回滚素材..."),
    QT_TRANSLATE_NOOP("RuntimeText", "Chrome 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "Chromium 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie Sentinel 初始化: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie Sentinel 启动失败（预期行为）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie Sentinel 文件不存在，将使用无 Cookie 模式下载（可能受限）"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie Sentinel 文件存在但未发现 {0} 相关 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie Sentinel 获取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie 不完整，缺少: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie 已刷新({0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie 文件不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie 校验未通过"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookie 格式化失败：提取到空列表"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookies 文件 (*.txt);;所有文件 (*.*)"),
    QT_TRANSLATE_NOOP("RuntimeText", "Cookies 文件疑似为 JSON 格式，yt-dlp 只支持 Netscape HTTP Cookie File 格式；已忽略该文件。"),
    QT_TRANSLATE_NOOP("RuntimeText", "EAC (立方体)"),
    QT_TRANSLATE_NOOP("RuntimeText", "Edge 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 不支持 v360"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 封面嵌入成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 未找到，无法嵌入封面"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 未找到，无法进行音量标准化"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 自定义路径无效，已忽略并回退自动检测: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FFmpeg 错误: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FLAC 封面嵌入失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Firefox 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL ({0}更新)"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL - X (Twitter) 安全登录"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL - YouTube 安全登录"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL {0} {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL {0} 已可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL 数据迁移已完成。删除本文件会让下次启动重新扫描旧数据位置。\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL 更新"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL 更新器启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "FluentYTDL 独立更新器"),
    QT_TRANSLATE_NOOP("RuntimeText", "Google 域 {0} 个 Cookie, names={1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "IsUserAnAdmin 调用失败，按无管理员权限处理: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "LibreWolf 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "MP3 封面嵌入失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Mesh (鱼眼)"),
    QT_TRANSLATE_NOOP("RuntimeText", "Mesh 格式暂不支持转码"),
    QT_TRANSLATE_NOOP("RuntimeText", "MessageBoxW 失败（用户看不到这次失败）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Minter 响应正常"),
    QT_TRANSLATE_NOOP("RuntimeText", "Minter 响应正常 (非 JSON)"),
    QT_TRANSLATE_NOOP("RuntimeText", "Minter 已初始化"),
    QT_TRANSLATE_NOOP("RuntimeText", "Minter 缓存正常 ({0} 条目)"),
    QT_TRANSLATE_NOOP("RuntimeText", "Minter 缓存正常 (条目: {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "OGG 封面嵌入失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Opera GX 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "Opera 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT HTTP 插件文件 (getpot_bgutil_http.py) 缺失"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager 进程 stderr: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager 进程 stdout: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: IT 重置后 Token 仍无效: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: IT 重置后 Token 验证通过: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: Integrity Token 已失效，将重新生成"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: Windows Job Object 已创建"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 使 Integrity Token 失效失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 使用端口 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 关联 Job Object 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 创建 Job Object 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 启动服务失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 已关闭残留服务 (端口 {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 开始健康检查 (PID: {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 恢复步骤 1/3 — 清除缓存"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 恢复步骤 2/3 — 重置 Integrity Token"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 恢复步骤 3/3 — 完整重启服务"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 无代理配置"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 服务已停止"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 服务已启动 (PID: {0}, 端口: {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 服务已在运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 服务未运行，尝试启动..."),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 服务未运行，跳过停止操作"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 未找到 POT Provider 可执行文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 注入代理 → {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 清除缓存失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 端口 {0} 已就绪"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 系统代理模式，继承环境（兼容 TUN）"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 缓存已清除"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 缓存清除后 Token 仍无效: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 缓存清除后 Token 验证通过: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 触发完整重启..."),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 读取代理配置失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 进程已终止，跳过停止操作"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Manager: 进程已退出 (返回码: {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: yt-dlp.exe 未找到，跳过同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 同步异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 复制 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 复制 {0} 失败（权限不足）。请以管理员身份运行一次应用以完成插件部署。"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 已同步 {0} 个插件文件到 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 插件已是最新，无需同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 插件源目录不存在，跳过同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 无法创建插件目录 {0}（权限不足）。如果安装在 Program Files 下，请以管理员身份运行一次，或手动复制插件文件。"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT Plugin Sync: 未找到插件源文件，跳过同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 加载失败，已停止本次请求：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 后台预热启动失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 基础插件文件 (getpot_bgutil.py) 缺失"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 插件已就位 ({0} 个文件，位于 yt-dlp.exe 旁)"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 插件目录不存在: {0}。请确保 sync_pot_plugins_to_ytdlp() 已正确执行。"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 服务未就绪，请检查服务状态和网络连接后重试。"),
    QT_TRANSLATE_NOOP("RuntimeText", "POT 服务未运行，无法注入 base_url（先启用并等待预热）"),
    QT_TRANSLATE_NOOP("RuntimeText", "PlaylistScheduler: 未知 task_id=%r (error)"),
    QT_TRANSLATE_NOOP("RuntimeText", "PlaylistScheduler: 未知 task_id=%r (finished)"),
    QT_TRANSLATE_NOOP("RuntimeText", "ProcessManager 初始化完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "Python.NET 加载失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "ROLLBACK: 还原到更新前的版本..."),
    QT_TRANSLATE_NOOP("RuntimeText", "SRT 格式缺少时间码"),
    QT_TRANSLATE_NOOP("RuntimeText", "ShellExecuteW 返回 {0}，提权失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 1: 解压新版本到临时目录..."),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 2: 验证解压结果..."),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 4: 重命名 _internal/ → _internal_old/ ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 5: 移动新文件到目标目录..."),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 6: 启动新版本: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 7: 看门狗接管 (watch_mode={0}, pid={1}, mode={2})"),
    QT_TRANSLATE_NOOP("RuntimeText", "Step 8: 发现 updater.exe.new，开始 updater 自更新"),
    QT_TRANSLATE_NOOP("RuntimeText", "Token 有效 (长度 {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "Token 格式异常: 长度={0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "Token 格式看起来不对（通常包含 'mweb' 或 'visitor'）"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 元数据注入成功"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 投影转换 (EAC -> Equi)..."),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 解析失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 解析失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 解析失败：yt-dlp 未返回有效元数据。"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 转换... ({0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "VR 转码失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "Vivaldi 浏览器"),
    QT_TRANSLATE_NOOP("RuntimeText", "WaitForSingleObject 返回异常值: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "WebM 容器不支持嵌入 SRT/ASS 等常用字幕。建议切换至 MKV 或 MP4。"),
    QT_TRANSLATE_NOOP("RuntimeText", "WebView2 模式：无缓存 Cookie，请在设置页点击「立即刷新」登录获取"),
    QT_TRANSLATE_NOOP("RuntimeText", "WebView2 登录成功，Cookie 已保存: {0} ({1} 个)"),
    QT_TRANSLATE_NOOP("RuntimeText", "WebView2 登录流程失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "WebView2 账号 {0} 的 Cookie 未通过校验，已保留原有 {1} 真相源: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "WorkerErrorDialog 已在显示，跳过本次"),
    QT_TRANSLATE_NOOP("RuntimeText", "X 平台 Cookie 不完整，缺少关键字段: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "YouTube Cookies 已关闭，本次请求不携带 Cookie。"),
    QT_TRANSLATE_NOOP("RuntimeText", "[AdminMode] 以管理员身份自动刷新Cookie: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[AdminMode] 手动文件模式，跳过自动刷新"),
    QT_TRANSLATE_NOOP("RuntimeText", "[AdminMode] 未配置Cookie来源，跳过自动刷新"),
    QT_TRANSLATE_NOOP("RuntimeText", "[AdminMode] 登录模式(WebView2)，跳过自动刷新（需要用户交互）"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CLI] extractor_args 键: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CLI] 添加参数: --extractor-args {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ChannelFlat] 解析完成: {0} 耗时 {1:.2f}s (tab={2}, entries={3})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] updater.exe 已启动: pid={0}, archive={1}, dest={2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] updater.exe 版本 {0} 过旧，不传 --data-dir/--origin-user-sid（updater 将退化为 survival 监护模式）"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 取不到当前用户 SID，不传 --origin-user-sid"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 启动 updater.exe 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 忽略过期 generation 的取消: {0} != {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 忽略过期 generation 的确认: {0} != {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 忽略重复的更新请求: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 无法查询活跃任务，按无任务处理: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 更新已批准 (gen={0})，请求优雅退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 有 {0} 个活跃任务，等待用户确认 (gen={1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 清单获取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 清单获取成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 状态 {0}，不启动 updater"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 状态 {0}，忽略取消"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 状态 {0}，忽略新的更新请求"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 状态 {0}，忽略确认"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 状态为 QUITTING 但没有 pending 更新"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 用户取消了更新 (gen={0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ComponentUpdate] 读取 PE 版本资源失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieRefreshWorker] 异常"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieRefreshWorker] 提取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] Cookie 文件缺少来源元数据"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] Cookie 来源不匹配: 现有={0}, 期望={1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] WebView2 {0} Cookie 同步完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] WebView2 {0} Cookie 未同步（沿用旧真相源）: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 尚无 WebView2 登录态，跳过同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 新 Cookie 不可用且无旧文件可回退: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 新 Cookie 不可用，已保留旧真相源: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 更新失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 真相源已更新: {1}（{2} 个 Cookie，来源 {3}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] {0} 静默更新失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 保存元数据失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 元数据已保存 ({0}): {1}, {2} cookies"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 发出启动健康度失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 启动健康度: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 启动时静默刷新失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 启动时静默刷新开始..."),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 启动时静默刷新异常（预期行为）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 启动时静默刷新成功：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 复制 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 已删除旧 Cookie 文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 已删除旧元数据文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 已同步手动导入的 Cookie 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 已迁移旧版 Cookie 元数据: {0} -> {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 已迁移旧版 Cookie 文件: {0} -> {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 强制刷新异常"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 手动导入的 Cookie 文件不可用，沿用旧真相源"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 提取了 {0} 个 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 未启用验证源，跳过静默刷新"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 清除文件失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 用户可在设置页点击'手动刷新'重试"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 用户触发强制刷新（允许 UAC）"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 读取 {0} WebView2 账号失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 读取Cookie文件失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 读取元数据失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 迁移旧版 Cookie 元数据失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CookieSentinel] 迁移旧版 Cookie 文件失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[CoverDirect] 提取失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[DialogExtract] 开始解析: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[DialogExtract] 解析失败: {0} 耗时 {1:.2f}s (build_opts={2:.0f}ms, 子进程轮次={3}) {4}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[DialogExtract] 解析完成: {0} 耗时 {1:.2f}s (build_opts={2:.0f}ms, 子进程轮次={3}, formats={4}, entries={5})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[DialogRender] 首屏可见耗时 {:.2f}s mode={} url={}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[EXE] 开始解析 URL: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Executor] 字幕嵌入 + webm → 强制 mkv"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Executor] 字幕嵌入 + {} → 强制 mkv"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Futures] 线程池任务异常 label={}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] Pillow 解码失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] SSL 警告 ({}): {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 代理 URL 无效: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 代理模式=手动，但 URL 为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 已启用磁盘缓存: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 磁盘缓存初始化失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 磁盘缓存清理失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 磁盘缓存清理：删除 {0} 个旧文件，当前 {1} MB"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ImageLoader] 配置代理: {}:{}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[LightweightExtract] yt-dlp 退出码 {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[LightweightExtract] 提取失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] Cookie 状态检查失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] on_worker_error 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] {0} Cookie 不可用: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] {0} Cookie 有效，启动静默"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] {0} 新 Cookie 被拒绝，仍在使用旧文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] {0} 未启用 Cookie，跳过启动提醒"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] 已恢复 {0} 个未完成任务到 UI"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] 收到更新申请，开始优雅退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "[MainWindow] 检测到软件更新: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Navigation] 侧边栏 panel 类型为 {0}，跳过可打断动画安装"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT] 开关切换处理失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Diagnose] 探测输出:\n{}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Diagnose] 检测异常"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Parse] 注入 base_url={0} warm=True port={1} url={2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Parse] 跳过注入 reason={0} url={1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Ready] 失败 stage=server_down (进程存活 pid={0} 但端口 {1} 不通)"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Ready] 失败 stage={0} {1} 将在 {2:.0f}s 后重试 (第 {3} 次)"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Ready] 服务就绪 port={0} pid={1} token_len={2} warm_ms={3:.0f} plugin={4} minter={5} deno={6}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Ready] 警告 stage=deno_missing — 未找到 deno.exe，POT 服务可能无法铸造 BotGuard Token。请在「设置 → 依赖组件」安装 JS Runtime (Deno)。"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][Ready] 警告 stage=plugin_missing {0} — 服务已就绪但 yt-dlp 无法加载插件，PO Token 不会被使用"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][{}] argv 已含 youtubepot-bgutilhttp base_url={}{}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][{}] argv 未含 POT 参数 (enabled=False){}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[POT][{}] argv 未含 POT 参数 (enabled=True){}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ParseCache] 命中 mode={0}: {1} 缓存年龄 {2:.1f}s 本次耗时 {3:.0f}ms (formats={4}, entries={5}) 桶: {6}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ParseCache] 已清空 {0} 条缓存{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ParseCache] 跳过写入: POT 预热中，键不稳定"),
    QT_TRANSLATE_NOOP("RuntimeText", "[ParseCache] 跳过写入: entries={0} 超过上限 {1}，deepcopy 成本高于收益"),
    QT_TRANSLATE_NOOP("RuntimeText", "[PlaylistFlat] 解析完成: {0} 耗时 {1:.2f}s (entries={2})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[SABR 追加 web_safari 重解析]"),
    QT_TRANSLATE_NOOP("RuntimeText", "[SABR] web_safari 重解析失败，沿用原结果: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[SABR] 检测到 SABR-only（高清直链被丢弃），已标记本次请求对应的账号或匿名会话；后续解析/下载将追加 web_safari 客户端。"),
    QT_TRANSLATE_NOOP("RuntimeText", "[SubEmbed] 未指定 → MKV"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Subtitle] 成功后诊断命中 {} (code={})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Subtitle] 迟解析取 info 失败，将回落正则模式：{}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[TaskDBWriter] 写入异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[TaskDBWriter] 批量写入回滚，改为逐条重试: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[Timing][run_dump_single_json] env={:.0f}ms 子进程={:.0f}ms JSON={:.0f}ms 输出={}行"),
    QT_TRANSLATE_NOOP("RuntimeText", "[UpdateNotifier] 更新通知已接入消息中心"),
    QT_TRANSLATE_NOOP("RuntimeText", "[UpdateNotifier] 跳过 {0}：有更新但没有下载地址"),
    QT_TRANSLATE_NOOP("RuntimeText", "[UrlRouter] t.co 展开失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[VR] 元数据注入失败，保留原文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "[VR] 无法找到最终文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2Runtime] 已检测到运行时，版本 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2Runtime] 未检测到 WebView2 运行时，登录模式不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] WebView2 缓存目录: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] code={0} stage={1} 子进程报告错误: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 启动安全登录窗口: {0} (session={1}, hidden_first={2})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 子进程已启动 (PID: {0}, session={1})，等待用户登录..."),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 子进程意外退出且未回传任何结果"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 子进程返回空 Cookie 列表"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 强制终止残留子进程"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 成功提取 {0} 个 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 提取过程异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 未收到子进程响应 (超时)"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 读取子进程队列异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[WebView2] 预检失败：缺少 WebView2 运行时，已跳过子进程启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "[cookie 刷新后重试]"),
    QT_TRANSLATE_NOOP("RuntimeText", "[cookie_runfile] 启动清理遗留运行副本: {0} 个"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] rc={} 只有警告级线索 {}，不采纳为主因"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 发现缺少 code 的规则，已跳过"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 已应用规则覆盖层，{} 条: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 未加载到任何内置规则，诊断将退化为兜底模式: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 没有任何有效 pattern，已跳过"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 的 category 非法（{}），归为 unknown"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 的 pattern kind 未知: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 的 pattern 缺少 value，已跳过"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 的 severity 非法（{}），归为 fatal"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则 {} 的正则无效（{}），已跳过: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则文件读取失败，已忽略: {} ({})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[diagnostics] 规则文件顶层不是对象，已忽略: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[skip=authcheck 重试]"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}/{1}] {2} — 后处理: {3}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}] Cookie 清洗完成: {1} -> {2} (移除: {3}, 其中已过期 {4} 个)"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}] Cookie 清洗完成: 无需过滤"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}] 导入文件 Cookie 清洗完成: {1} -> {2} (移除: {3})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}] 导入文件 Cookie 清洗完成: 保持 {1} 个"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] X 域 {1} 个 Cookie, names={2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] YouTube 域 {1} 个 Cookie, names={2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] 尚未检测到 LOGIN_INFO"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] 尚未检测到完整的登录 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] 等待跳回 X... (当前: {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] 等待跳回 YouTube... (当前: {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "[{0}s] 超过 {1}s 未检测到有效登录态，主动显示窗口让用户登录..."),
    QT_TRANSLATE_NOOP("RuntimeText", "[全局] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[冲突] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[失败] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[字幕 ({0})]"),
    QT_TRANSLATE_NOOP("RuntimeText", "[字幕] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[字幕处理] ✓ 已就绪 {0} 个字幕文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "[封面] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[封面嵌入] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[封面嵌入] ✓ 成功"),
    QT_TRANSLATE_NOOP("RuntimeText", "[封面嵌入] 正在处理: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[播放列表] {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "[无登录态降级]"),
    QT_TRANSLATE_NOOP("RuntimeText", "[频道标签降级]"),
    QT_TRANSLATE_NOOP("RuntimeText", "_on_download_clicked 异常"),
    QT_TRANSLATE_NOOP("RuntimeText", "android_vr 解析失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "commit gate: 本次已被取消"),
    QT_TRANSLATE_NOOP("RuntimeText", "cookie 运行副本启动清理失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "create_window 成功"),
    QT_TRANSLATE_NOOP("RuntimeText", "create_window 成功 (fallback, 无 hidden)"),
    QT_TRANSLATE_NOOP("RuntimeText", "discovery 已封板，reconcile() 不再可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "discovery 已封板，{0}() 不再可用（生产请走 register_generated）"),
    QT_TRANSLATE_NOOP("RuntimeText", "drop 必须给出 reason"),
    QT_TRANSLATE_NOOP("RuntimeText", "ffmpeg 剪切失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "gc_orphans 失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "group_stem 未确定，build_plan() 拒绝猜测"),
    QT_TRANSLATE_NOOP("RuntimeText", "import webview 成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen FLAC 封面嵌入成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen MP3 封面嵌入成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen OGG 封面嵌入成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen 不支持 {0} 格式"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen 库不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "mutagen 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "provider 拒绝了请求（服务不可达时会静默降级）：\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "psutil 未安装，进程清理功能受限"),
    QT_TRANSLATE_NOOP("RuntimeText", "py7zr 解压失败 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "pywebview 加载失败: {0}\n{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "register_generated 必须给出 producer"),
    QT_TRANSLATE_NOOP("RuntimeText", "register_generated: {0!r} 不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "replace_artifact_content: {0!r} 不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "replace_artifact_content: {0!r} 是空文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "rookiepy 不支持 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "rookiepy 未安装，无法从浏览器提取 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "rookiepy 未安装，浏览器 Cookie 自动提取功能不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "t.co 短链接"),
    QT_TRANSLATE_NOOP("RuntimeText", "updater.exe 不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "webview.start() 已返回（子进程即将退出）"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp JSON 解析失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 信息提取失败 (rc={0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 可执行文件未找到"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 安装后置处理失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 执行失败 (退出码: {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 执行错误: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 未输出可解析的 JSON\n{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 输出里没有任何 POT 痕迹 —— 插件很可能没被加载。\n退出码={0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "yt-dlp 退出码 {} (非零)，但输出文件有效 ({}, {:.1f} KB)。忽略错误。"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0!r} 不在 {1!r} 内"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0!r} 与 {1!r} 不同卷"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0:,} 次观看"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} Cookie Sentinel: {1} (更新于 {2}, {3} 个 {4} Cookie)"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} Minter 缓存：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} Token 生成：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} v130+ 使用了 App-Bound 加密。\n需要以管理员身份重新启动程序才能提取 Cookie。\n\n建议：使用 Edge 或 Firefox 浏览器可避免此问题。"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} yt-dlp 主动探测（-v，验证插件被加载且 provider 被选中）："),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} yt-dlp 插件：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} {1} 已可用（当前 {2}），前往「设置 → 更新」即可更新。"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} {1} 已可用，前往「设置 → 更新」即可更新。"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 个字幕文件全部校验失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 分钟前"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 天前"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 将从 {1} 频道切换到 {2} 频道（{3} → {4}），前往「设置 → 更新」即可应用。"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 小时前"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 提取失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 有新版本 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 服务进程："),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 格式不支持封面嵌入: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 自动修复："),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 需要切换频道"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 需要管理员权限才能提取 Cookie（App-Bound 加密）"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0} 默认账号"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}-结尾"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}: PATH 上找到 {1}，但缺少 {2}，不计为可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}: 无法保留目的地原有副本，本项跳过（下次启动重试）"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}: 目的地已是最新，保持不动"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}: 采用来自 {1} 的版本"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}{1} | ⬇️ {2} | {3}/{4} | 剩余: {5}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}分钟前"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}（来自 {1}）副本校验未通过，该候选不参与裁决"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}（来自 {1}）已保留为 {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}，{1:.0f}s 后重试预热（已失败 {2} 次）"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}，{1} 秒后开始…"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}，尝试 py7zr"),
    QT_TRANSLATE_NOOP("RuntimeText", "{0}；py7zr 依赖加载失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "{} 条字幕已嵌入容器，不再单独交付"),
    QT_TRANSLATE_NOOP("RuntimeText", "ℹ️ 当前以普通用户身份运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏭️ 正在标记/跳过赞助片段..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⏳ Cookie 将在 {0} 分钟后过期，建议提前刷新。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏳ {0}（等待 {1} 秒）"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏳ 剩余: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏳ 提取超时 ({0}s)"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏸️ 下载已暂停"),
    QT_TRANSLATE_NOOP("RuntimeText", "⏸️ 下载已暂停 (应用重启)"),
    QT_TRANSLATE_NOOP("RuntimeText", "▶️ 继续下载..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚙️ 正在执行后期处理 ({0})..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠ MP4 容器包含多条音轨（已选 {0} 种）时，在部分自带播放器中可能无法切换音频或出现异常。\n建议使用 MKV 容器或专业播放器（如 VLC/PotPlayer）。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠ WebM 容器对多音轨支持有限，合并过程可能报错。强烈建议切换至 MKV。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ [SABR] 该账号处于 SABR-only 灰度，已追加 web_safari 客户端以拿回高清直链 (player_client={0})。此策略为待观察项。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ get_cookies 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ queue 发送失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ {0} 新 Cookie 未通过校验，仍在使用旧真相源: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ {0} 格式不支持封面嵌入\n原因：{1}\n下载将继续，但不会嵌入封面图片。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ {0} 格式封面嵌入支持有限\n备注：{1}\n封面可能无法正确显示在某些播放器中。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ {0} 视频在 MP4 中的播放兼容性取决于播放器。若无法播放，可尝试 MKV 或其他编码。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ {0}，解析可能失败。建议前往设置页刷新 Cookie。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 字幕文件异常: {0}（{1}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 封面嵌入工具不可用"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 提取任务未能完成（应用已重启）"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 标题声称 8K 但最高格式仅 {0}p，可能是 VR 视频"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 获取 Google Cookie 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 警告: 该视频受限，最高仅支持 {0}p 提取"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 请求的语言没有可用字幕"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚠️ 部分播放器不支持 MP4 中的 Opus 音频。可尝试 MKV，或选择 AAC 音轨。"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 下载中..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 检测到纯图片直接下载，走极简通道"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 检测到纯提取任务 (skip_download)，走快速原生通道"),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 正在下载图片..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 正在初始化提取引擎..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 正在直接下载封面图片..."),
    QT_TRANSLATE_NOOP("RuntimeText", "⚡ 正在获取字幕或封面..."),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 正在下载裁切片段 | "),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 正在整理裁切文件…"),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 正在精确裁切与重编码 {0:.1f}% | 速度: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 片段下载完成，正在准备精确裁切…"),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 裁切下载 · {0} {1:.1f}% | 已写入 {2}/{3} | ⬇️ {4} | 媒体速度 {5}"),
    QT_TRANSLATE_NOOP("RuntimeText", "✂️ 裁切下载 · {0} | 已写入 {1}/{2} | ⬇️ {3}"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ Cookie 已更新（{}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ android_vr 客户端获取到 {0} 个格式"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 下载完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 下载并处理完成！"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 回退解析成功: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 已加载 Cookie 文件: {0} (YouTube/Google cookies: {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 已合并 {0} 个 VR 高分辨率格式 (IDs: {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 已回传 {0} 个 Cookie 到父进程"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 当前以管理员身份运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 提取完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "✅ 无登录态降级解析成功（格式列表可能不完整）"),
    QT_TRANSLATE_NOOP("RuntimeText", "✓ 字幕文件有效: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "✗ 字幕文件无效: {} - {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ {0} 与 WebM 不兼容。"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ {0} 与 WebM 不兼容，强烈建议使用 MP4 或 MKV。"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ 更新异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ 格式化后为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ 登录未完成，请重新点击「点击登录」"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ 错误: yt-dlp 退出码 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "❌ 错误: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "【提取解密失败】\n\n受到 {0} 最新的底层加密机制 (App-Bound Encryption) 限制，目前第三方工具无法直接解密提取它的 Cookie。\n\n请执行以下任一替代方案：\n1. 切换到不受此限制的浏览器 (推荐: Firefox 或 LibreWolf)\n2. 使用「手动导入」方式 (前往设置选择\"手动导入 cookies.txt\"并提供导出的文件)"),
    QT_TRANSLATE_NOOP("RuntimeText", "下载 URL 为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "下载: {0:.1f}%"),
    QT_TRANSLATE_NOOP("RuntimeText", "下载失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "下载已取消: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "下载流完毕，等待后续合并与处理..."),
    QT_TRANSLATE_NOOP("RuntimeText", "下载过程发生未知异常: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "不下载字幕"),
    QT_TRANSLATE_NOOP("RuntimeText", "不支持为 {0} 格式嵌入封面"),
    QT_TRANSLATE_NOOP("RuntimeText", "不支持的平台"),
    QT_TRANSLATE_NOOP("RuntimeText", "不支持的归档格式: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "不支持的链接"),
    QT_TRANSLATE_NOOP("RuntimeText", "主媒体登记失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "主程序可执行文件名"),
    QT_TRANSLATE_NOOP("RuntimeText", "主程序的用户数据目录（.update_ready 信号落点）。为空则退化为 survival 监护"),
    QT_TRANSLATE_NOOP("RuntimeText", "主进程 PID"),
    QT_TRANSLATE_NOOP("RuntimeText", "互动提醒"),
    QT_TRANSLATE_NOOP("RuntimeText", "交叉验证：minter 缓存现有 {0} 条。"),
    QT_TRANSLATE_NOOP("RuntimeText", "产物对账失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "产物校验未通过，已保留沙盒供排查"),
    QT_TRANSLATE_NOOP("RuntimeText", "产物校验未通过，已保留沙盒供排查：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "产物登记失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "从 {0} 到结束"),
    QT_TRANSLATE_NOOP("RuntimeText", "从 {0} 提取到 {1} 个 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "从 {0} 提取失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "从模型移除第 {0} 行失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "代理地址已变更"),
    QT_TRANSLATE_NOOP("RuntimeText", "代理模式已变更"),
    QT_TRANSLATE_NOOP("RuntimeText", "代理配置注入失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "任务已取消"),
    QT_TRANSLATE_NOOP("RuntimeText", "任务终态失败（不可重试）: {} — {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "估算中"),
    QT_TRANSLATE_NOOP("RuntimeText", "使用内置 FFmpeg: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "使用系统 FFmpeg: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "使用系统代理"),
    QT_TRANSLATE_NOOP("RuntimeText", "使用缓存的 Cookie 文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "保留落选的 {0}（来自 {1}）失败: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "信号处理注册失败 (可忽略): {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "全局: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "内嵌 7za version=unknown"),
    QT_TRANSLATE_NOOP("RuntimeText", "内嵌 7za version={0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "内嵌 7za 不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "内嵌 7za 无法启动: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "内置"),
    QT_TRANSLATE_NOOP("RuntimeText", "内部哨兵：本进程由 _elevate_self 提权启动，禁止再次提权（防 UAC 递归）"),
    QT_TRANSLATE_NOOP("RuntimeText", "写入真相源失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "写出 {0} 失败，updater 将按超时回滚: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "写探测失败（目录不可写）: {0} — {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "刚刚"),
    QT_TRANSLATE_NOOP("RuntimeText", "创建登录窗口失败: {0}\n{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "删除 WebView2 账号存储目录失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "删除历史行 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "删除通知失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "刷新失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "刷新异常: "),
    QT_TRANSLATE_NOOP("RuntimeText", "刷新异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "剪切操作超时"),
    QT_TRANSLATE_NOOP("RuntimeText", "剪贴板自动识别已关闭"),
    QT_TRANSLATE_NOOP("RuntimeText", "剪贴板自动识别已开启"),
    QT_TRANSLATE_NOOP("RuntimeText", "加载 WebView2 账号配置失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "加载配置文件失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "加载验证配置失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "单语言字幕: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "即将删除 {0} 个源文件，是否继续？"),
    QT_TRANSLATE_NOOP("RuntimeText", "即将删除 {0} 个缓存文件，是否继续？"),
    QT_TRANSLATE_NOOP("RuntimeText", "历史行 {0} 没有可用的 ydl_opts，无法直接重下"),
    QT_TRANSLATE_NOOP("RuntimeText", "原始格式选择已保存: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "发现新版本 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "发现预发布版本 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "发起更新的原用户 TokenUser SID（S-1-5-21-...），用于降权启动的身份准入"),
    QT_TRANSLATE_NOOP("RuntimeText", "取消裁决失败（沙盒留给 GC）: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "只有 media 能 promote，{0} 是 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "只看到 POT 相关输出，但没有 bgutil provider 的痕迹：\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "合并后共 {0} 个, core匹配={1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "同步当前 WebView2 账号 Cookie 到统一文件失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "后处理: {0} ({1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "后处理: {0}..."),
    QT_TRANSLATE_NOOP("RuntimeText", "后处理中..."),
    QT_TRANSLATE_NOOP("RuntimeText", "后处理功能 {} 发生异常: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "后处理异常 ({0}): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "启动 GC 失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "启动 updater 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "启动更新 worker 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "启动登录窗口失败: {0}\n{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "启动组件版本探测线程失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "填充内容"),
    QT_TRANSLATE_NOOP("RuntimeText", "处理"),
    QT_TRANSLATE_NOOP("RuntimeText", "处理中"),
    QT_TRANSLATE_NOOP("RuntimeText", "复制 {0}（来自 {1}）失败: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "多次解析后它始终不涨，说明 Token 根本没被 yt-dlp 请求。"),
    QT_TRANSLATE_NOOP("RuntimeText", "多语言字幕: {0}{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "失败任务保留天数已更新为: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "失败裁决失败（沙盒留给 GC）: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "失败，见下方明细"),
    QT_TRANSLATE_NOOP("RuntimeText", "媒体流"),
    QT_TRANSLATE_NOOP("RuntimeText", "子进程内部异常: {0}\n{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕下载未启用"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕下载未启用，跳过后处理"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕后处理失败: {}（reason={}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕后处理开始 - output_path={}"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕后处理异常: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕嵌入未完成，已保留外置字幕文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕文件校验失败：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕未命中任何可用语言（想要 {0}；该视频只有 {1}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "字幕状态回调异常"),
    QT_TRANSLATE_NOOP("RuntimeText", "安装 {0}（来自 {1}）失败: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入 Cookie 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入失败（保留旧 Cookie）"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入失败，继续使用 {0} 的 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入底层异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入未生效: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "导入过程异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面嵌入失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面嵌入完成: {0} → {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面嵌入异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面嵌入成功"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面嵌入未产出文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "封面文件不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "将下载 {0}:{1:02d} 的片段"),
    QT_TRANSLATE_NOOP("RuntimeText", "将从 {0} 自动提取 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "将在下次成功提取后更新 Cookie 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "将跳过: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "尚无 Cookie 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "尚未登录获取 Cookie，请在设置页点击「立即刷新」"),
    QT_TRANSLATE_NOOP("RuntimeText", "工具未找到: {0}. 请将相应可执行文件放入 'bin' 目录，或将其加入系统 PATH，或在设置中指定路径。"),
    QT_TRANSLATE_NOOP("RuntimeText", "已从 {0} 提取 Cookie（管理员权限）"),
    QT_TRANSLATE_NOOP("RuntimeText", "已保留较新的一份，另一份存放在数据目录的 legacy_conflict_* 子目录中：\n{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已关闭"),
    QT_TRANSLATE_NOOP("RuntimeText", "已关闭元数据嵌入"),
    QT_TRANSLATE_NOOP("RuntimeText", "已关闭封面嵌入"),
    QT_TRANSLATE_NOOP("RuntimeText", "已关闭解析后窗口置顶"),
    QT_TRANSLATE_NOOP("RuntimeText", "已关闭：加速播放列表解析（实验性）"),
    QT_TRANSLATE_NOOP("RuntimeText", "已写出 {0} (pid={1}) → {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已写出数据迁移完成标记"),
    QT_TRANSLATE_NOOP("RuntimeText", "已切换到 WebView2 账号 {0}，并同步 Cookie 到 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已删除 {0} 个文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "已删除文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "已删除文件残留"),
    QT_TRANSLATE_NOOP("RuntimeText", "已加载验证配置: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已启动管理员权限进程，当前进程退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "已启用 JS runtime: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已启用内置 FFmpeg: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已启用内置 JS runtime: deno ({0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "已存在名为 '{0}' 的账号，请使用其他名称"),
    QT_TRANSLATE_NOOP("RuntimeText", "已安装 (无版本输出)"),
    QT_TRANSLATE_NOOP("RuntimeText", "已完成 {0} 个视频 · 总计 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已完成 {0}/{1} · {2} 个失败 · 总计 {3}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已将旧 WebView2 缓存迁移到账号 {0}: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已将账号目录隔离至新路径: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已就位"),
    QT_TRANSLATE_NOOP("RuntimeText", "已就绪（端口 {0}{1}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "已开启元数据嵌入（标题、作者、描述等）"),
    QT_TRANSLATE_NOOP("RuntimeText", "已开启解析后窗口置顶"),
    QT_TRANSLATE_NOOP("RuntimeText", "已更新"),
    QT_TRANSLATE_NOOP("RuntimeText", "已更新为手动导入的 Cookie 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "已注入自定义代理: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已清理 {0} 个子进程"),
    QT_TRANSLATE_NOOP("RuntimeText", "已清理 {0} 个文件残留"),
    QT_TRANSLATE_NOOP("RuntimeText", "已清理陈旧的 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已生成 Cookie 文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "已经是管理员权限，无需重启"),
    QT_TRANSLATE_NOOP("RuntimeText", "已请求管理员重启，当前进程即将退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "已读取 cookies.txt，但未发现 YouTube/Google 域相关 cookies。请确认是在 youtube.com 登录后导出，且为 Netscape 格式。"),
    QT_TRANSLATE_NOOP("RuntimeText", "已过滤域名: {0}等"),
    QT_TRANSLATE_NOOP("RuntimeText", "已过滤无关 Cookie: {0}等"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选 {0} 条音轨"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选 {0} 条音轨 ✓"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选 {0} 种字幕 ✓"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选 {0} 种语言 ✓"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} / {1} 项"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} 个类别"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} 个类别: "),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} 封面"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} 种字幕语言。为便于保留多条字幕，建议使用 MKV；MP4 的播放支持取决于播放器。"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择 {0} 种语言"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选择: "),
    QT_TRANSLATE_NOOP("RuntimeText", "已选：{0} 条音轨（请再选择一个视频流）"),
    QT_TRANSLATE_NOOP("RuntimeText", "已选：视频流 + {0} 条音轨"),
    QT_TRANSLATE_NOOP("RuntimeText", "已配置 PO Token，但当前未加载有效 Cookies。mweb.gvs PO Token 通常需要配合 cookies 使用。"),
    QT_TRANSLATE_NOOP("RuntimeText", "已验证 (检测到 X 平台登录)"),
    QT_TRANSLATE_NOOP("RuntimeText", "已验证 (检测到 YouTube 登录)"),
    QT_TRANSLATE_NOOP("RuntimeText", "应用图标资源缺失，标题栏与启动图将没有图标"),
    QT_TRANSLATE_NOOP("RuntimeText", "应用安装目录"),
    QT_TRANSLATE_NOOP("RuntimeText", "建议在设置中临时关闭代理后重试解析。"),
    QT_TRANSLATE_NOOP("RuntimeText", "开始"),
    QT_TRANSLATE_NOOP("RuntimeText", "开始 WebView2 登录流程（账号: {0}）..."),
    QT_TRANSLATE_NOOP("RuntimeText", "开始解析 URL: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "强制直连 (禁用代理)"),
    QT_TRANSLATE_NOOP("RuntimeText", "当前 WebView2 账号 ({0}) 尚无 Cookie 缓存，跳过同步"),
    QT_TRANSLATE_NOOP("RuntimeText", "当前 {0} 账号: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "当前: {0}  |  最新: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "当前进程已具备管理员权限，无需提权"),
    QT_TRANSLATE_NOOP("RuntimeText", "恢复状态失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "成功"),
    QT_TRANSLATE_NOOP("RuntimeText", "成功处理 {0} 个字幕文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "成功添加 {0} 个任务"),
    QT_TRANSLATE_NOOP("RuntimeText", "手动导入"),
    QT_TRANSLATE_NOOP("RuntimeText", "手动导入文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "手动导入的 Cookie 文件不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "手动导入的 Cookie 文件不存在或无效"),
    QT_TRANSLATE_NOOP("RuntimeText", "托盘图标资源缺失，已跳过系统托盘初始化"),
    QT_TRANSLATE_NOOP("RuntimeText", "找到 {0} 个有效 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "抓帧失败 ({0}s): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "抓帧失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "抓帧操作超时"),
    QT_TRANSLATE_NOOP("RuntimeText", "挂起等待修复..."),
    QT_TRANSLATE_NOOP("RuntimeText", "探测执行失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "探测超时（>{0:.0f}s）"),
    QT_TRANSLATE_NOOP("RuntimeText", "接入 Observability sink 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "推送通知失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "提交后观测失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "提交失败: {0!r}"),
    QT_TRANSLATE_NOOP("RuntimeText", "提交迁移标记失败，下次启动将重试: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "提取 {0} Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "提取异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "提取源 {0} 已停止支持，已自动迁移到 Edge"),
    QT_TRANSLATE_NOOP("RuntimeText", "提取过程异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "提权失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "插件检测异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "播放列表解析失败 (耗时 {0:.2f}s): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "播放列表解析失败：返回结果为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "播放列表过长 ({0}), 将截断前 {1} 个强制逐条入队..."),
    QT_TRANSLATE_NOOP("RuntimeText", "数据迁移：目的地 {0}，遗留候选 {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "整合流（视频 + 音频）"),
    QT_TRANSLATE_NOOP("RuntimeText", "整组避让超过 {0} 次仍撞名: {1!r}"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件不存在，请检查路径是否正确"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件为空或格式无效"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件内容为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件大小 ({}) 为预期 ({}) 的 {:.0%}，低于预期但仍判定为有效（预期由 {} 个流累计）"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件大小 ({}) 仅为预期大小 ({}) 的 {:.0%}，判定为不完整下载"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件大小为 0"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件夹删除残留"),
    QT_TRANSLATE_NOOP("RuntimeText", "文件有效"),
    QT_TRANSLATE_NOOP("RuntimeText", "新版本"),
    QT_TRANSLATE_NOOP("RuntimeText", "新版本启动失败，已还原到旧版本。\n\n旧版本正在启动，你的配置与下载记录都还在。请稍后重新检查更新。\n\n详细日志：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无可用字幕"),
    QT_TRANSLATE_NOOP("RuntimeText", "无效的时间格式: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无权限终止进程 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法从 {0} 提取 Cookie\n\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法从 {0} 提取 Cookie\n\n可能的原因：\n1. {1} 未安装\n2. 未在 {2} 中登录 YouTube\n3. {3} 正在运行（Cookie 数据库被锁定）\n\n建议：\n• 确保已在浏览器中登录 YouTube\n• 完全关闭浏览器后重试\n• 尝试使用其他浏览器（如 Edge）"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法准备嵌入落点: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法在 {0} 写下 {1}（只读位置，可忽略）"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法检查磁盘空间: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法生成唯一文件名"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法确定 {0} 落点，跳过: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法确定磁盘: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法获取当前版本"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法解析时间: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "无法识别该 X 平台链接类型"),
    QT_TRANSLATE_NOOP("RuntimeText", "日志 {0}（来自 {1}）与现有文件不同，已另存为 {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "时间不能为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "昨天"),
    QT_TRANSLATE_NOOP("RuntimeText", "显示窗口失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "智能选择字幕（中文→英语→日语）"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新 worker 进程错误: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新 worker 退出码 {0}: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新Cookie状态显示失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新器退出 (COMMIT)"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新器退出 (ROLLBACK)"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新失败: {0}\n（保留旧 Cookie 可用）"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新已完成，但找不到新版本的可执行文件。\n\n{0}\n\n请从开始菜单或桌面快捷方式手动启动 FluentYTDL。\n\n详细日志：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新已完成，但新版本没能自动启动。\n\n请手动双击 FluentYTDL 图标启动程序，你的配置与下载记录都还在。\n\n详细日志：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新归档不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新归档文件路径 (7z/zip)"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能完成：{0} 正被占用，无法替换。\n\n{1}\n\n请确认 FluentYTDL 已完全退出（检查任务管理器与托盘图标）后重试。\n已还原到更新前的状态，程序可以照常使用。\n\n详细日志：{2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能完成：复制新版本文件时出错，已还原到旧版本。\n\n程序可以照常使用。请稍后重新检查更新。\n\n详细日志：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能完成：更新包内容不完整，已中止。\n\n程序本体未被改动，可以照常使用。请稍后重新检查更新。\n\n详细日志：{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能完成：更新包解压失败。\n\n{0}\n\n程序本体未被改动，可以照常使用。请稍后重新检查更新。\n\n详细日志：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能完成：程序文件正被占用，无法替换。\n\n{0}\n\n请确认 FluentYTDL 已完全退出（检查任务管理器与托盘图标）后重试。\n程序本体未被改动，可以照常使用。\n\n详细日志：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能开始：找不到已下载的更新包。\n\n{0}\n\n请重新在设置页检查更新。程序本体未被改动，可以照常使用。\n\n详细日志：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "更新未能开始：没有权限修改安装目录。\n\n{0}\n\n如果刚才的管理员授权对话框被取消，请重新检查更新并选择「是」。\n程序本体未被改动，可以照常使用。\n\n详细日志：{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "替代品 {0} 当前 presence={1}，不能顶位"),
    QT_TRANSLATE_NOOP("RuntimeText", "有 {0} 个已获取格式的条目最高画质低于 {1}p。\n\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "有 {0} 项迁移失败（通常是文件被占用），下次启动会自动重试。旧数据仍在原位置，未被删除。"),
    QT_TRANSLATE_NOOP("RuntimeText", "服务已起但未就绪"),
    QT_TRANSLATE_NOOP("RuntimeText", "服务未运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "服务未运行，跳过主动探测"),
    QT_TRANSLATE_NOOP("RuntimeText", "未启用"),
    QT_TRANSLATE_NOOP("RuntimeText", "未启用验证"),
    QT_TRANSLATE_NOOP("RuntimeText", "未命名账号"),
    QT_TRANSLATE_NOOP("RuntimeText", "未安装"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到 JS runtime: {0}。请安装并加入 PATH（推荐 deno），或在设置中填写可执行文件路径。"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到 yt-dlp.exe。请检查自定义内核路径、应用托管目录或系统 PATH。"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到 yt-dlp.exe（既没有内置也不在 PATH 中）"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到 —— POT 可能铸不出 Token，请在「核心组件」安装"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到字幕文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到字幕文件（清单里没有字幕产物）: video={} candidates={}"),
    QT_TRANSLATE_NOOP("RuntimeText", "未找到有效 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "未提取到有效的 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "未检测到 Microsoft Edge WebView2 运行时，无法使用登录模式。\n请前往以下地址安装后重试，或在设置中改用「浏览器提取」/「手动导入」：\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "未检测到 deno，已自动启用 {0} 作为 JS runtime（建议优先安装 deno）。"),
    QT_TRANSLATE_NOOP("RuntimeText", "未检测到任何受支持的 JS runtime（deno/node/bun/quickjs）。YouTube 解析可能缺失大量格式。建议安装 deno 并加入 PATH。"),
    QT_TRANSLATE_NOOP("RuntimeText", "未检测到有效 Cookies，将使用无 Cookie 默认模式"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知 kind: {0!r}"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知大小"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知标题"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知格式，尝试使用 ffmpeg 嵌入"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知链接"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知错误"),
    QT_TRANSLATE_NOOP("RuntimeText", "未知页面"),
    QT_TRANSLATE_NOOP("RuntimeText", "未获取到字幕：已请求 {0}，但一个文件都没写出"),
    QT_TRANSLATE_NOOP("RuntimeText", "未获取到字幕：已请求 {0}，但一个文件都没写出（可能被限速或需要 PO Token）"),
    QT_TRANSLATE_NOOP("RuntimeText", "未获取到字幕：按正则模式请求 {0}，yt-dlp 没有匹配到任何字幕轨道"),
    QT_TRANSLATE_NOOP("RuntimeText", "未解析出任何 Cookie（可能不是 Netscape 格式）"),
    QT_TRANSLATE_NOOP("RuntimeText", "未读取"),
    QT_TRANSLATE_NOOP("RuntimeText", "未运行"),
    QT_TRANSLATE_NOOP("RuntimeText", "未选择任何类别"),
    QT_TRANSLATE_NOOP("RuntimeText", "未配置验证源，请先在设置中选择浏览器或导入 Cookie 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "未验证"),
    QT_TRANSLATE_NOOP("RuntimeText", "本进程已是提权实例（--elevated），跳过提权检查"),
    QT_TRANSLATE_NOOP("RuntimeText", "来源文件不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "标记全部通知已读失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "标记通知已读失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "格式化后 {0} 个 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "检查"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测 GPU 编码器失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到 'The page needs to be reloaded'，正在自动刷新 WebView2 Cookie 并重试一次..."),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到 Chrome v130+ App-Bound 加密，需要管理员权限"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到 Chromium 严格依赖本地执行的 App-Bound 加密拒绝解密"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到 Program Files 目录，尝试请求管理员权限..."),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到 winget 安装的 deno，但未在 PATH 中；已自动使用: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到两处旧数据"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到播放列表 authcheck 限制提示，按 yt-dlp 官方建议自动启用 youtubetab:skip=authcheck 并重试一次。"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测到频道 authcheck 限制，自动启用 youtubetab:skip=authcheck 并重试。"),
    QT_TRANSLATE_NOOP("RuntimeText", "检测失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "正在下载... {0}%"),
    QT_TRANSLATE_NOOP("RuntimeText", "正在下载更新... {0}%"),
    QT_TRANSLATE_NOOP("RuntimeText", "正在从 {0} 提取 Cookies，请稍候..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在从 {0} 提取..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在以管理员权限提取 {0} Cookie..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在使用 AtomicParsley 嵌入封面..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在使用 FFmpeg 嵌入封面..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在使用 mutagen 嵌入封面..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在保存: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "正在加载频道{0}（{1}）..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在解析链接 {0}/{1}..."),
    QT_TRANSLATE_NOOP("RuntimeText", "正在重试..."),
    QT_TRANSLATE_NOOP("RuntimeText", "沙盒清理失败（成品不受影响）"),
    QT_TRANSLATE_NOOP("RuntimeText", "没有任何可交付成员，build_plan() 拒绝产出空计划"),
    QT_TRANSLATE_NOOP("RuntimeText", "没有任何链接解析成功。"),
    QT_TRANSLATE_NOOP("RuntimeText", "没有可用的封面嵌入工具"),
    QT_TRANSLATE_NOOP("RuntimeText", "注入 VR 元数据..."),
    QT_TRANSLATE_NOOP("RuntimeText", "注册子进程 PID {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "注销子进程 PID {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "流协议 {0} 需要 yt-dlp native 处理"),
    QT_TRANSLATE_NOOP("RuntimeText", "浏览器 Cookie 提取完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "消息中心: 收到新通知 [{0}] {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "清单未获取"),
    QT_TRANSLATE_NOOP("RuntimeText", "清单里有 {} 个字幕文件，开始校验"),
    QT_TRANSLATE_NOOP("RuntimeText", "清单里没有 {0!r}"),
    QT_TRANSLATE_NOOP("RuntimeText", "清理回调失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "清理旧备份目录 _internal_old/ ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "清理残留的 _update_tmp/ 目录..."),
    QT_TRANSLATE_NOOP("RuntimeText", "清理解析缓存失败（不影响主流程）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "清空通知失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "片头"),
    QT_TRANSLATE_NOOP("RuntimeText", "片尾"),
    QT_TRANSLATE_NOOP("RuntimeText", "状态不可用（{0}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "状态：{0} · {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "环境 PATH"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户关闭了登录窗口"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户取消下载"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户取消了管理员权限请求 (返回码: {0})"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户在结果页要求重新解析"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户在设置页手动清空"),
    QT_TRANSLATE_NOOP("RuntimeText", "用户手动重试解析"),
    QT_TRANSLATE_NOOP("RuntimeText", "画质检查暂停"),
    QT_TRANSLATE_NOOP("RuntimeText", "画质检查：连续 {0} 个任务未达标，触发队列暂停阈值"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录失败，未返回 Cookie 数据"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录窗口意外退出且未回传结果，请查看登录子进程日志。"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录结果读取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录获取 (WebView2 - {})"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录获取 (WebView2)"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录获取 (推荐)"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录超时 ({0}s)，未检测到有效的登录 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "登录超时，未收到 Cookie 数据"),
    QT_TRANSLATE_NOOP("RuntimeText", "百分浏览器 (Cent)"),
    QT_TRANSLATE_NOOP("RuntimeText", "目标 {0}p → 实际 {1}p"),
    QT_TRANSLATE_NOOP("RuntimeText", "目标 {0}p → 最高可用 {1}p"),
    QT_TRANSLATE_NOOP("RuntimeText", "目标目录不可写且未获得管理员权限，中止更新（未做任何改动）"),
    QT_TRANSLATE_NOOP("RuntimeText", "目标目录不可写（自定义只读安装位置），尝试请求管理员权限..."),
    QT_TRANSLATE_NOOP("RuntimeText", "直接提取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "短链接展开失败，请手动在浏览器打开复制完整链接"),
    QT_TRANSLATE_NOOP("RuntimeText", "磁盘空间不足: {0} MB"),
    QT_TRANSLATE_NOOP("RuntimeText", "磁盘空间不足！\n需要: {0}\n可用: {1}\n缺少: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "磁盘空间严重不足: {0} MB"),
    QT_TRANSLATE_NOOP("RuntimeText", "移动 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "移动文件失败，执行完整回滚..."),
    QT_TRANSLATE_NOOP("RuntimeText", "空间充足 (需要 {0}，可用 {1})"),
    QT_TRANSLATE_NOOP("RuntimeText", "端点不存在 (旧版本，跳过)"),
    QT_TRANSLATE_NOOP("RuntimeText", "第 {0}/{1} 次自动重试"),
    QT_TRANSLATE_NOOP("RuntimeText", "等待下载..."),
    QT_TRANSLATE_NOOP("RuntimeText", "等待主进程退出..."),
    QT_TRANSLATE_NOOP("RuntimeText", "等待进程 {0} 超时 ({1}s)"),
    QT_TRANSLATE_NOOP("RuntimeText", "等待进程退出的超时秒数"),
    QT_TRANSLATE_NOOP("RuntimeText", "红灯 下载已暂停: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "组件下载无响应超时，终止 worker: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "组件版本探测失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "终止进程 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "结束时间必须大于开始时间"),
    QT_TRANSLATE_NOOP("RuntimeText", "绿灯 下载已恢复: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "编码错误"),
    QT_TRANSLATE_NOOP("RuntimeText", "编辑 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "缺少 .youtube.com 登录态 Cookie（LOGIN_INFO / SID / SAPISID / __Secure-1PSID 之一）"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络检测异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络状态: 不稳定"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络状态: 断开"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络状态: 稳定"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络监控已停止"),
    QT_TRANSLATE_NOOP("RuntimeText", "网络监控已启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "自动(推荐)"),
    QT_TRANSLATE_NOOP("RuntimeText", "自动刷新 WebView2 Cookie 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "自动刷新 WebView2 Cookie 异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "自动刷新 WebView2 Cookie 成功，准备重试解析"),
    QT_TRANSLATE_NOOP("RuntimeText", "自定义"),
    QT_TRANSLATE_NOOP("RuntimeText", "自定义: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "自我推广"),
    QT_TRANSLATE_NOOP("RuntimeText", "至少需要保留一个 {0} WebView2 账号，拒绝删除"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取 Cookie 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取时长失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取未读通知数失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取磁盘空间失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "获取视频时长失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频 + 音频分流"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频总时长: {0}:{1:02d}。格式: 1:30 或 1m30s 或 90 (秒)"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频文件不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频文件不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频文件不存在，无法进行字幕后处理: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "视频流"),
    QT_TRANSLATE_NOOP("RuntimeText", "解压失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "解压验证失败，中止更新"),
    QT_TRANSLATE_NOOP("RuntimeText", "解压验证通过"),
    QT_TRANSLATE_NOOP("RuntimeText", "解析中..."),
    QT_TRANSLATE_NOOP("RuntimeText", "解析失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "解析失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "解析失败：yt-dlp 未返回有效元数据（可能被要求登录/验证）。请在弹窗中启用浏览器 Cookies 重试。"),
    QT_TRANSLATE_NOOP("RuntimeText", "解析结果保留时间已关闭"),
    QT_TRANSLATE_NOOP("RuntimeText", "警告: VERSION 文件不存在（非致命）"),
    QT_TRANSLATE_NOOP("RuntimeText", "警告: 等待超时，尝试继续替换..."),
    QT_TRANSLATE_NOOP("RuntimeText", "计算中"),
    QT_TRANSLATE_NOOP("RuntimeText", "记录生效配置快照失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "该视频最高仅支持 {0}p，请确认是否继续下载。"),
    QT_TRANSLATE_NOOP("RuntimeText", "请求以管理员身份重启: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "请求失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "请求管理员重启失败"),
    QT_TRANSLATE_NOOP("RuntimeText", "读取失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "读取数据迁移报告失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "读取来源文件失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "读取通知失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "调用 webview.start() ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "赞助广告"),
    QT_TRANSLATE_NOOP("RuntimeText", "超时"),
    QT_TRANSLATE_NOOP("RuntimeText", "跨卷复制后主媒体过小: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "跨卷复制大小不符: {0} != {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "跳过 VR 转码: 分辨率过高 ({0}p)"),
    QT_TRANSLATE_NOOP("RuntimeText", "输入文件不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "迁移日志 {0}（来自 {1}）失败: {2}"),
    QT_TRANSLATE_NOOP("RuntimeText", "迁移旧 WebView2 缓存失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "迁移有 {0} 项失败，下次启动将重试（不写 {1}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "迁移账号 {0} Cookie 文件失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "迁移账号目录失败 {0}: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "运行中 (端口 {0}), {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "运行中但 Token 生成异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "运行中（127.0.0.1:{0}）"),
    QT_TRANSLATE_NOOP("RuntimeText", "返回内容非 JSON"),
    QT_TRANSLATE_NOOP("RuntimeText", "还有 {0} 个已勾选条目正在补全信息。\n\n"),
    QT_TRANSLATE_NOOP("RuntimeText", "这看起来不是一个 .exe 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "进程 {0} 不存在或已退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "进程 {0} 已退出"),
    QT_TRANSLATE_NOOP("RuntimeText", "进程扫描失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "连续 {0} 个任务画质未达标，已暂停排队中的 {1} 个任务。请检查源视频的可用格式、目标分辨率和访问权限后再继续。"),
    QT_TRANSLATE_NOOP("RuntimeText", "连续画质未达标，排队任务已暂停"),
    QT_TRANSLATE_NOOP("RuntimeText", "选择"),
    QT_TRANSLATE_NOOP("RuntimeText", "选择 Cookies 文件"),
    QT_TRANSLATE_NOOP("RuntimeText", "选择 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "选择下载目录"),
    QT_TRANSLATE_NOOP("RuntimeText", "通过 py7zr 解压完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "通过 zipfile 解压完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "通过内嵌 7za 解压完成"),
    QT_TRANSLATE_NOOP("RuntimeText", "部分数据未能迁移"),
    QT_TRANSLATE_NOOP("RuntimeText", "配置为 {0}，但提取失败，当前使用 {1} 的 Cookie"),
    QT_TRANSLATE_NOOP("RuntimeText", "重命名 _internal 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "重命名 {0} → {1}.old ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "重命名 {0} 失败: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "重新尝试下载..."),
    QT_TRANSLATE_NOOP("RuntimeText", "链接不能为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: _internal/ 下找不到 python3*.dll（归档不完整）"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: _internal/ 目录不存在或为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: _internal/base_library.zip 不存在或大小为 0（归档不完整）"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: {0} 不存在或大小为 0"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: 归档文件不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: 新版本 {0} 不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误: 目标目录不存在: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "错误详情：\n{0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "队列已自动暂停"),
    QT_TRANSLATE_NOOP("RuntimeText", "降档前移除旧 worker 失败（继续）: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "降档重建 worker 失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "降级解析也失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "非 Windows 系统不支持自动提权重启"),
    QT_TRANSLATE_NOOP("RuntimeText", "非音乐部分"),
    QT_TRANSLATE_NOOP("RuntimeText", "音量标准化失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "音量标准化完成: {0} → {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "音量标准化异常: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "音量标准化未产出文件: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "音频{0}k"),
    QT_TRANSLATE_NOOP("RuntimeText", "音频或封面文件不存在"),
    QT_TRANSLATE_NOOP("RuntimeText", "音频流"),
    QT_TRANSLATE_NOOP("RuntimeText", "预发布版本"),
    QT_TRANSLATE_NOOP("RuntimeText", "预告"),
    QT_TRANSLATE_NOOP("RuntimeText", "预热中…（端口 {0}，解析等待 POT 就绪）"),
    QT_TRANSLATE_NOOP("RuntimeText", "频道 {0} 标签页解析出错: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "频道当前标签页不存在，自动尝试回退解析: {0} ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "频道标签页 {0} 任务异常: {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "频道解析失败 (耗时 {0:.2f}s): {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "频道解析失败: {}"),
    QT_TRANSLATE_NOOP("RuntimeText", "频道解析失败：返回结果为空"),
    QT_TRANSLATE_NOOP("RuntimeText", "首次启动，默认使用 WebView2 登录获取验证"),
    QT_TRANSLATE_NOOP("RuntimeText", "验证失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "验证源变化: {0} -> {1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "验证源已设置: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "默认语言"),
    QT_TRANSLATE_NOOP("RuntimeText", "，Token 长度 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "，minter 缓存 {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "𝕏 推文视频"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎉 [VR] 最高可用分辨率: {0}p (8K)"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎉 最高可用分辨率: {0}p (8K)"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎬 YouTube 播放列表"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎬 YouTube 短视频"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎬 YouTube 视频"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎬 YouTube 频道"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎬 视频流"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎯 检测到 LOGIN_INFO! 用户已完成登录。"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎯 检测到 auth_token! 用户已完成登录。"),
    QT_TRANSLATE_NOOP("RuntimeText", "🎵 正在提取独立音频流..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🎵 音频流"),
    QT_TRANSLATE_NOOP("RuntimeText", "🏷️ 正在写入视频元数据 (标题/作者)..."),
    QT_TRANSLATE_NOOP("RuntimeText", "💥 _background_poll 未捕获异常: {0}\n{1}"),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 字幕"),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 正在下载字幕..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 正在保存字幕..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 正在保存字幕: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 正在内嵌字幕轨道..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📝 正在转换字幕格式..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📡 导航到 accounts.google.com ..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📡 正在获取流媒体元数据..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📦 数据流"),
    QT_TRANSLATE_NOOP("RuntimeText", "📦 正在整理文件..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📦 正在无损合并音视频 (FFmpeg)..."),
    QT_TRANSLATE_NOOP("RuntimeText", "📺 [VR] 最高可用分辨率: {0}p"),
    QT_TRANSLATE_NOOP("RuntimeText", "📺 [VR] 最高可用分辨率: {0}p (4K)"),
    QT_TRANSLATE_NOOP("RuntimeText", "📺 最高可用分辨率: {0}p (4K)"),
    QT_TRANSLATE_NOOP("RuntimeText", "🔁 [SABR] 本次请求首次检测到 SABR，正在追加 web_safari 客户端重新解析以拿回高清档…"),
    QT_TRANSLATE_NOOP("RuntimeText", "🔄 使用 android_vr 客户端获取 VR 高分辨率格式..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🔄 切片下载超时，正在重试... {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🔄 检测到认证封锁，丢弃 Cookie 使用无登录态客户端重试..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🔄 网络请求失败，正在重试... {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🔍 正在拉取元数据..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🔍 正在解析目标地址..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🔐 已注入手动 PO Token：将优先尝试 mweb 客户端"),
    QT_TRANSLATE_NOOP("RuntimeText", "🖼️ 封面"),
    QT_TRANSLATE_NOOP("RuntimeText", "🖼️ 正在下载视频封面图..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🖼️ 正在嵌入视频封面图..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🖼️ 正在转换视频封面图..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🗑️ 任务已取消并清理残骸"),
    QT_TRANSLATE_NOOP("RuntimeText", "🚀 Cookies 模式激活：交由 yt-dlp 自动管理最优客户端组合"),
    QT_TRANSLATE_NOOP("RuntimeText", "🚀 _background_poll 线程已启动"),
    QT_TRANSLATE_NOOP("RuntimeText", "🚀 准备启动执行器..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🚀 启动下载..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🚚 正在移动文件..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🚪 用户关闭了登录窗口"),
    QT_TRANSLATE_NOOP("RuntimeText", "🚫 SponsorBlock 已启用: 将标记以下类别为章节: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🚫 SponsorBlock 已启用: 将移除以下类别: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🛡️ 质量守卫报告 ({0} 项异常)"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 [VR] android_vr 解析完成: {0} 个格式"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 [VR] 使用 android_vr 客户端解析: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 [VR] 投影检测: {0} / {1} (Equi={2}, Mesh={3}, EAC={4})"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 [VR] 解析失败: {0}"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 检测到 VR 关键词: '{0}'"),
    QT_TRANSLATE_NOOP("RuntimeText", "🥽 检测到 VR 投影格式 (mesh)"),
    QT_TRANSLATE_NOOP("RuntimeText", "🧩 正在组装 m3u8 碎片地图..."),
    QT_TRANSLATE_NOOP("RuntimeText", "🧾 正在核对产物..."),
)
# fmt: on
# END GENERATED MARKERS
